### ISSUE TITLE
Open lineage demo notebook

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-samples#33]
**see note below - purpose changed **

Open lineage support should be configured in the vdc helm charts as a demo

* See open-metadata-implementation/user-interfaces/access-services-user-interface/src/main/resources/application.properties for additional properties required for the user interface
* .... more requirements tbd.....

**Comment by cmgrote** [comment]
All of the notebooks are currently in the core repository, not this one...  (Though maybe the fact that this issue is here implies that it would be logical to move the notebooks here as well, per https://github.com/odpi/egeria-jupyter-notebooks/issues/4?)

**Comment by planetf1** [comment]
:-) I did move the issue out with the thought that would be the case (and no work on vdc in the interim), but you are correct that the move hasn't been done yet. 

With a PR open in the base for a open lineage notebook, and discussions there on moving, perhaps this issue can be closed in any case.

**Comment by planetf1** [comment]
I did open up https://github.com/odpi/egeria-charts/issues/172 - so suggest  we close this one now (as we mentioned last year!) - consolidating!
