### ISSUE TITLE
Security: ibmigc.username and ibmigc.password 

### ISSUE THREAD

**Issue by zoranid** [odpi/egeria-samples#4]
When using external IBM IGC user needs to supply ibmigc.username and ibmigc.password in values.yaml. This is a security issue because once configmap is deployed somebody can use e.g. 
kubectl get configmap gaudy-dragon-odpi-egeria-vdc-configmap -o yaml --export 
and obtain ibmigc username and password. Preferably, ibmigc.username and ibmigc.password should be made a k8s secret.

**Comment by planetf1** [comment]
The VDC environment will need significant re-work to adapt to the many changes made in Egeria to better support
metadata integration. Additionally the helm charts used for the lab & a simple base config have evolved to better support
different types of services, exposing of ports, persistent storage etc.

As such specific incremental changes to the current - now old - charts do not really add value.

As such closing for now
